{{- $barhelper_api_key := default (randAlphaNum 64) .Values.barhelperPassword.value | b64enc | quote }}
{{- $mqtt_password := default (randAlphaNum 64) .Values.mqttPassword.value | b64enc | quote }}
{{- $secretName := default "plaato" .Values.existingSecrets }}

{{- if .Values.existingSecrets }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $existingSecret }}
{{- $barhelper_api_key = index $existingSecret.data "BARHELPER_API_KEY"}}
{{- $mqtt_password = index $existingSecret.data "MQTT_PASSWORD"}}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: "plaato"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  BARHELPER_API_KEY: {{ $barhelper_api_key }}
  MQTT_PASSWORD: {{ $mqtt_password }}