apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-plaato-keg.fullname" . }}
  labels:
    {{- include "open-plaato-keg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.keg.port }}
      targetPort: {{ .Values.service.keg.port }}
      protocol: TCP
      name: keg
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "open-plaato-keg.selectorLabels" . | nindent 4 }}
