jobs:
  timeZone: "Etc/UTC"
#  - name: reader
#    namespace: default
#    image:
#      repository: ghcr.io/djtecha/rss_parser
#      tag: v0.12.1
#      imagePullPolicy: IfNotPresent
#    schedule: "*/2 * * * *"
#    failedJobsHistoryLimit: 1
#    successfulJobsHistoryLimit: 1
#    concurrencyPolicy: Allow
#    restartPolicy: OnFailure
#    imagePullSecrets:
#      name: "rss-reader"
#    volumes:
#      - name: rss-feed
#        persistentVolumeClaim:
#          claimName: rss-feed
#    volumeMounts:
#      - mountPath: "/tmp"
#        name: rss-feed
#    env:
#      - name: BREVO_API
#        valueFrom:
#          secretKeyRef:
#            name: brevo-api
#            key: BREVO_API
#    command: ["python3"]
#    args:
#      - "app.py"
#      - "-c"
#      - "config.yaml"
#      - "--ignore_email"
