# Default values for calibre-web-automated.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: crocodilestick/calibre-web-automated
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  http:
    port: 8083
    type: ClusterIP

resources: {}

livenessProbe:
  httpGet:
    path: /login
    port: http
readinessProbe:
  httpGet:
    path: /login
    port: http

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: config
volumeMounts:
  - mountPath: "/config"
    name: config

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  storageClass: ""
  existingClaim: ""
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  additionalVolumes:
    - name: nfs
      nfs:
        server: nfs.hiddennode.us
        path: /storage02/media
        readOnly: true
  additionalMounts:
    - name: nfs
      mountPath: "/storage02/media"

env:
  - name: TZ
    value: "UTC"
#  - name: DOCKER_MODS
#    value: "lscr.io/linuxserver/mods:universal-calibre-v7.16.0"
