# Default values for open-plaato-keg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/sklopivo/open-plaato-keg
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  http:
    port: 8085
    type: ClusterIP
  keg:
    port: 1234
    type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /api/alive
    port: http
readinessProbe:
  httpGet:
    path: /api/alive
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: plaato-db
    persistentVolumeClaim:
      claimName: plaato-db
volumeMounts:
  - mountPath: "/db"
    name: plaato-db

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64

persistence:
  storageClass: ""
  existingClaim: ""
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  # if you need any additional volumes, you can define them here
  additionalVolumes: []
  # if you need any additional volume mounts, you can define them here
  additionalMounts: []

existingSecrets: "open-plaato-keg"

barhelperPassword:
  value: ""
mqttPassword:
  value: ""

env:
  - name: DATABASE_FILE_PATH
    value: "/db/keg_data.bin"
  - name: KEG_LISTENER_PORT
    value: "1234"
  - name: HTTP_LISTENER_PORT
    value: "8085"
  - name: MQTT_ENABLED
    value: "true"
  - name: MQTT_HOST
    value: "192.168.0.123"
  - name: MQTT_PORT
    value: "1883"
  - name: MQTT_CLIENT
    value: "open_plaato_keg"
  - name: BARHELPER_ENABLED
    value: "false"
  - name: BARHELPER_UNIT
    value: "l"
  - name: BARHELPER_KEG_MONITOR_MAPPING
    value: "plaato-auth-key:barhelper-custom-keg-monitor-id"
  - name: BARHELPER_ENDPOINT
    value: "https://europe-west1-barhelper-app.cloudfunctions.net/api/customKegMon"
  - name: MQTT_USERNAME
    value: ""
  - name: MQTT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: open-plaato-keg
        key: MQTT_PASSWORD
  - name: BARHELPER_API_KEY
    valueFrom:
      secretKeyRef:
        name: open-plaato-keg
        key: BARHELPER_API_KEY