# Default values for open-plaato-keg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/sklopivo/open-plaato-keg
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  keg_listener_port: 1234
  http_listener_port: 8085

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: DATABASE_FILE_PATH
    value: "/db/keg_data.bin"
  - name: KEG_LISTENER_PORT
    value: 1234
  - name: HTTP_LISTENER_PORT
    value: 8085
  - name: MQTT_ENABLED
    value: true
  - name: MQTT_HOST
    value: 192.168.0.123
  - name: MQTT_PORT
    value: 1883
  - name: MQTT_USERNAME
    value: ""
  - name: MQTT_PASSWORD
    value: ""
  - name: MQTT_CLIENT
    value: "open_plaato_keg"
  - name: BARHELPER_ENABLED
    value: false
  - name: BARHELPER_API_KEY
    value: ""
  - name: BARHELPER_KEG_MONITOR_MAPPING
    value: "plaato-auth-key:barhelper-custom-keg-monitor-id"
