{{- range $job := .Values.jobs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "cronjobs.releaseName" $ }}-{{ $job.name }}"
  namespace: {{ $job.namespace }}
data:
  {{- $job.configMapData | toYaml | nindent 2 }}
{{- end }}
