{{- range $job := .Values.jobs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "cronjobs.releaseName" $ }}-{{ $job.name }}"
  namespace: {{ $job.namespace }}
data:
  config: |-
    {{ $job.config }}
{{- end }}
